Second task - API fetching
mbmjertan/wp-task pull request #2
Opened 2021-07-02 15:41 UTC by mbmjertan

This pull request:
* changes the project name (https://github.com/mbmjertan/wp-task/commit/198ea419680b4b60f2c22a41420015c0e8ded781) for more consistent naming
* fixes code standards noncompliance in Blocks.php due to an extra space in the array (https://github.com/mbmjertan/wp-task/commit/d5ec486083acb66a223b121927fe15117487ad02)
* implements the SpaceNews class used to retrieve data from spaceflightnewsapi.net (https://github.com/mbmjertan/wp-task/commit/96b4d9dd6fc82e38a9b5586fdb7fefdb29ee8820)
* * based upon the example class in Eightshift
* * the `fetch` method retrieves the latest space flight news and returns a presentable response - it can be limited in number of news to fetch using the `limit` parameter, and set to fetch only news with `id` less than a value using the `lt` parameter (useful for loading older news)
* * * the method replaces `WP_Error` instances returned by `wp_remote_get` with a new `WP_Error` instance to avoid leaking error data, and strips away everything apart from the response body in case the request was successful 
* bootstraps the `space-news` route (https://github.com/mbmjertan/wp-task/commit/0999ad1c54af738f97bf0f2c73912725f39c4990)

It remains to implement the limit / filtering options on the route itself. The class could be better abstracted, but it seems as an overkill to do so to fetch a row of space news. I also focused on using native PHP and WordPress functions instead of relying on libraries such as Guzzle.

However, some PHPStan and PHPCS errors occur, mostly in Eightshift's files. [See this gist for the errors.](https://gist.github.com/mbmjertan/19cc16e9d61d160e096749e1b1b79bd1)

I'm not sure what to do about the `WordPress.WP.GlobalVariablesOverride.Prohibited` errors, but it seems as the WordPress globals aren't in scope in files in which the errors occur. As for the PHP compatibility error in `SpaceNews.php`, is it okay to change the PHP version requirements in `composer.json`? Nothing seems to crash on PHP 8.0.7 :)

2021-07-05 08:34 UTC, dingo-d commented
Hi @mbmjertan !

> I'm not sure what to do about the WordPress.WP.GlobalVariablesOverride.Prohibited errors, but it seems as the WordPress globals aren't in scope in files in which the errors occur. As for the PHP compatibility error in SpaceNews.php, is it okay to change the PHP version requirements in composer.json? Nothing seems to crash on PHP 8.0.7 :)

WP Globals sniff is, in most cases, just a false positive one, because phpcs doesn't know about the context of the file (whether it's a template file or not). So you can ignore it.

As for PHP 8, while I myself work on it, for client stuff we still work with PHP 7.4, just because WP Core is not compatible fully with PHP8, not tested with it, and the majority of the plugins are not tested with PHP8. So we just avoid it for the time being. I'd like to think that by the end of the year the state of WP core will be in a better place for PHP8 compatibility.

Oh, and we also haven't fully tested our backend libs with PHP 8 so it's safer to use 7.4.

If you have PHP 8 locally installed, I recommend using [phpenv](https://github.com/phpenv/phpenv) package to easily switch between the versions 🙂

2021-07-05 08:46 UTC, dingo-d commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
Do you think this is the best way of adding a dependency in a class? Are there any other ways to do it, and what would the benefits/flaws be of those approaches?

2021-07-05 08:46 UTC, IvanGrginovInf commented
>  not sure what to do about the WordPress.WP.GlobalVariablesOverride.Prohibited errors, but it seems as the WordPress globals aren't in scope in files in which the errors occur.

For the purposes of this task you can ignore them. In general, we need to fix those in in the component view in https://github.com/infinum/eightshift-frontend-libs

> As for the PHP compatibility error in SpaceNews.php, is it okay to change the PHP version requirements in composer.json? Nothing seems to crash on PHP 8.0.7 :)

This is also fine. Usually, you would do this anyway to reflect the PHP version of the project you're working on. Tho do take note of the comment from Denis regarding PHP 8.

2021-07-05 08:47 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +	private string $APIVersion = 'v3';
Already a v3! That's a lot of iterations 😄 Why 3?

2021-07-05 08:52 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +	}
The way we imagined organizing and using the classes is to separate the code into two major parts:

Service classes - they interact with the underlying WordPress core using hooks (actions/filters)
Regular classes - used to contain other logic, not necessarily tied to the WP hooks system

Since you don't have any filter inside this class, that means you don't need to implement the `ServiceInterface` and use the `register` method. That way, those classes won't interact with registering the hooks, and just be a part of the regular service injection process.

So you can either just remove the class, or you can maybe see if you could implement a separate interface for it.

Can you tell me what would be added benefit of having an interface for a class such as this?

2021-07-05 08:53 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +		$query = http_build_query($params);
Is there a WordPress equivalent of this PHP method? Can you explain why you'd use a WP one instead of PHP (or maybe why you wouldn't 😄)?

2021-07-05 08:57 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +		return $response;
I'd refactor this according to the return early principle

https://torquemag.io/2018/04/code-review-part-1-fixing-design-flaw-return-early-strategy/

Try to see if you can refactor this code 🙂

2021-07-05 08:57 UTC, dingo-d requested changes
Good work so far! Love the detailed documentation, and adding arguments is a nice touch for the REST API 🙂 

Also, love the detailed PR description, it's nice to see the explanation of someone's work 👍🏼

2021-07-05 09:04 UTC, IvanGrginovInf requested changes
Left some comments, otherwise looks good!

2021-07-05 09:04 UTC, IvanGrginovInf commented on unicornia/src/SpaceNews/SpaceNews.php
> +		// The response is rewritten to avoid leaking third-party API data, as well as error information.
Good thinking

2021-07-05 09:04 UTC, IvanGrginovInf commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$limit = $request->get_param('limit') ? (int)$request->get_param('limit') : null;
Is this kind of mixed type variable necessary? Ideally you'd keep all variable types consistent (i.e. if it's an `int`, keep it an `int` all the time rather than `int|null`).

Then you also wouldn't need to have properties in `fetch()` method nullable.

You can also define the type of the arguments in WP Rest Routes.

2021-07-05 09:41 UTC, mbmjertan commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
It's not the best way: this way of adding dependencies creates a new instance of the SpaceNews class, which isn't necessary here (wouldn't be, if the method was static) and can for instance be memory intensive for classes with a lot of properties. 

As class properties don't actually change in the SpaceNews class, it'd make more sense to declare the fetch method as static and the properties as class constants - it eliminates the need to construct a class instance which saves memory and shaves a bit off the CPU time, while also ensuring there aren't any unwanted side-effects (on the class, at least) from the method and making intentions more clear.

Otherwise, if we had a method that actually had an effect on class members (which I actually planned when coding the class) it'd make more sense to do this, as in that case we're relying on a specific class instance and have a need to change its properties. An example of where this would be the better approach would be, for instance, a `changePassword` method on a `User` model in a MVC framework.

2021-07-05 09:45 UTC, IvanGrginovInf commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
> As class properties don't actually change in the SpaceNews class, it'd make more sense to declare the fetch method as static and the properties as class constants

Good overview tho things should be static only if there's really no other way.

Also this is really simple as we've solved this problem in boilerplate using Autowiring, see https://infinum.github.io/eightshift-docs/docs/basics/autowiring/

2021-07-05 09:47 UTC, mbmjertan commented on unicornia/src/SpaceNews/SpaceNews.php
> +	private string $APIVersion = 'v3';
That's actually the version number for the API I'm using, the [Spaceflight News API](https://spaceflightnewsapi.net/). I find it just more aesthetically pleasing to separate the API iteration from the API base, so that's why it's in an variable of its own. How there's a _third_ iteration of such an API, I'm not sure either :sweat_smile:

2021-07-05 10:13 UTC, mbmjertan commented on unicornia/src/SpaceNews/SpaceNews.php
> +	}
Makes sense, thanks for the explanation!

I couldn't actually find this explanation of the conceptual differences between service and regular classes in Eightshift's docs, so I ended up building upon [the example class](https://infinum.github.io/eightshift-docs/docs/basics/example-class) and just not registering anything / implementing the interface. 

As benefits of having _this_ interface in _this particular class_ go, I can't actually think of any compelling uses for it, as I can't really find a use for a hook in this class: we're just fetching something from an API, and there's really no reason for this to have any impact on WordPress execution. 

As benefits of having an _interface_ in general go, interfaces make class interoperability easier by specifying which methods must be implemented in a class that implements an interface: all services classes, for instance, must implement the register method as declared in the ServiceInterface, so it can be called on any service class and can be expected to do the same thing. 

For instance, here it could make sense to declare something like `ApiInterface` with a `fetch` method - but I'd avoid doing that as different APIs could have different parameters (e.g., a MailChimp API integration won't have a single method with `limit` and `before` parameters), and it seems to me that abstracting anything in this particular case is premature. (There's one class doing it's thing) In larger projects, something like the `ClientInterface` from @infinum/eightshift-forms (https://github.com/infinum/eightshift-forms/blob/develop/src/Integrations/ClientInterface.php) would make sense. 

All being said, I think that transforming this class into a regular class is the way to go here.

2021-07-05 10:20 UTC, mbmjertan commented on unicornia/src/SpaceNews/SpaceNews.php
> +		$query = http_build_query($params);
There is a WordPress equivalent in the `build_query` function. (And `add_query_arg`, if we're looking at alternatives as well :))

I ended up using the PHP version because the WordPress one assumes that the parameters are already URL encoded (https://developer.wordpress.org/reference/functions/build_query/), but in general, WordPress core functions are supposed to follow best practices for the things they do (which is _your job_ when using PHP functions) and behave consistently across WordPress installations (which isn't always the case with PHP functions). But I think that's a valid question to ask yourself before using any ready-made function.

2021-07-05 10:34 UTC, mbmjertan commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$limit = $request->get_param('limit') ? (int)$request->get_param('limit') : null;
> Is this kind of mixed type variable necessary? Ideally you'd keep all variable types consistent (i.e. if it's an `int`, keep it an `int` all the time rather than `int|null`).

It isn't necessary: it'd be valid to revert to default here if `limit` is set to `0` (and allow 0 to be passed as a parameter). In the case that `0` would be a sensible value for the parameter, it'd be necessary to distinguish a valid value from a parameter not set, in which case introducing a mixed type seems to be a better approach.

> Then you also wouldn't need to have properties in `fetch()` method nullable.

That's true, yeah.

2021-07-05 10:44 UTC, dingo-d commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
@mbmjertan Thanks for the explanation. I was thinking more along the way of dependency injection (DI). Have you worked with DI before? What is the biggest benefit of DI in your opinion (if you've worked with it)?

2021-07-05 10:46 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +	private string $APIVersion = 'v3';
Ok, kinda makes sense 😄 

Although, since you are writing this API (this particular endpoint), you are actually creating something new, even though your API implementation uses some third-party data. So it's totally legit to put `v1` here 🙂 

The separation of concerns (putting it in a separate variable) is a good call 👍🏼

2021-07-05 10:58 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +	}
Your explanation for the `ApiInterface` is actually spot on 👍🏼 You'd define a fetch method, maybe adding some general parameters (URL, attributes) and that's it. 

Then you can create multiple instances of fetching classes that implement this interface but in a completely different way (fetching logic depends on the API implementation). You can go as far as to say: the `fetch` method in this interface will return an `ApiResponseDto` - [data transfer object](https://stitcher.io/blog/laravel-beyond-crud-02-working-with-data).

That way you will define a specific response structure that you'll use in your API. Making it super flexible. The downside is having some more boilerplate code for the DTO's, but the advantage is that you can plug in whatever third-party API you want without breaking how the response looks like (super important if you are working with mobile apps that consume your API for instance).

You don't have to do that here ofc, just removing the interface will suffice, but I do advise using DI in your code to use the fetch method.

2021-07-05 11:00 UTC, dingo-d commented on unicornia/src/SpaceNews/SpaceNews.php
> +		$query = http_build_query($params);
Yup, that's true. The advantage of working with core functions is that you are already working with WP 'framework', so it's good to use WP core functions and API, because you can reap the most benefits (security, caching, etc.).

👍🏼

2021-07-05 11:23 UTC, mbmjertan commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
@dingo-d Sorry for the confusion! I do have some experience with dependency injection, mostly from Laravel.

I think that in this instance it's sensible to just instantiate the needed dependency like this, as there isn't any other class in the project at this point we can use here apart from `SpaceNews`. However, if the `ApiInterface` was implemented and we had for instance multiple API sources, we could use a setter method which takes as a parameter a class implementing `ApiInterface` and call the fetch method of that class in `routeCallback`, which would allow switching the API used with ease.

I think that DI's biggest benefit is decreasing coupling between a class and its dependencies, relying only on the interface implemented, which makes code more maintainable in the long run and allows for easier refactoring. For instance, you could have an interface `MailerInterface` and classes `PostmarkClient`, `MailChimpClient` and `SMTPClient` which implement such an interface - DI makes it easy to switch which actual mailer is used.

2021-07-05 11:30 UTC, IvanGrginovInf commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$limit = $request->get_param('limit') ? (int)$request->get_param('limit') : null;
Good explanation, if `limit: 0` is a valid value to be passed to the news API then all is good!

2021-07-05 11:47 UTC, dingo-d commented on unicornia/src/Rest/Routes/SpaceNewsRoute.php
> +		$spaceNewsService = new SpaceNews();
Awesome 🙂 Thanks for the explanation, that's what I was aiming at 😄

2021-07-06 00:24 UTC, mbmjertan commented
I've went ahead and implemented the things we've talked about. 

`SpaceNews` isn't a `ServiceClass` anymore and it implements `NewsApiInterface`  which is just a simple abstraction of `SpaceNews` with a single fetch method. The `fetch` method of `SpaceNews` also returns early. `SpaceNewsRoute` uses DI and the number validation code has been extracted into a separate method. The code now also uses camelCase variable names and is standards compliant.

Thank you for all the comments, hope this is better now :)

2021-07-06 07:11 UTC, dingo-d approved these changes
Awesome!

2021-07-06 08:14 UTC, IvanGrginovInf approved these changes

2021-07-06 12:54 UTC, merged