Third task - Gutenberg block
mbmjertan/wp-task pull request #3
Opened 2021-07-05 00:07 UTC by mbmjertan

This PR implements the Gutenberg block. It includes changes from #2.

New commits:
* implement a news block for the block editor (https://github.com/mbmjertan/wp-task/commit/efbd00ae69bd9d66a85100436504dab9913d7aea)
* remove unused variable, imports (https://github.com/mbmjertan/wp-task/commit/6788139942ae95e350086f081564549c8c13391b)
* provide a view for the News block (https://github.com/mbmjertan/wp-task/commit/9ebd63a418ec1a8a3ca223de8c8a4c7f8466dc8a)
* add basic styling to the news block (https://github.com/mbmjertan/wp-task/commit/84f9f1bb601df223e1a57d96212d45ce26041b44)
* add Load more functionality (https://github.com/mbmjertan/wp-task/commit/6d71c0ee4853a8809a6c5eee8f0c69a84543caa6)
* change keywords for block (https://github.com/mbmjertan/wp-task/commit/77c79d94946ec634cfce33050b94e5f47b5df3eb)

This was my first encounter with Eightshift's development kit, and I couldn't figure out what's the go-to way to implement block attributes. I didn't feel like it was right to bug you guys on a Sunday night, so I'm leaving this as a draft to get some feedback. It works, but I'm not sure it's the best way to go.

Also, I wasn't completely sure what the task actually entailed implementing, as the block was supposed to be server side rendered (as per the hint :)) and the design made it clear that it was supposed to feature 'load more' functionality. In the end, I decided to render a four element row of content in PHP and provide additional row load functionality in JavaScript on the frontend via the REST route implemented in #2. I hope that's what you had in mind :)

In any case, I'd be really glad to hear feedback on this pull request, especially as Eightshift's development kit seems really cool and I'd like to work with it in the future.

2021-07-05 09:37 UTC, IvanGrginovInf requested changes
Left a couple of coments, other than that looks great, love that you used existing components  in your `news` block and the general amount of documentation / comments you added, gj!

Also didn't leave comments for classes that were in the previous PR: https://github.com/mbmjertan/wp-task/pull/2#pullrequestreview-698943747

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        postBlock.querySelectorAll('.block-news__post__tags__tag')[0].innerText = post.newsSite;
You should use classes prefixed with `js-` for selecting things in JS files. Also no need to use BEM for this. So in this case you can add tags as `.js-block-news-tag`.

This way you know that the class in question is used in a JS file and if you or somebody else down the line would remove / change it, they immediately know they broke some part of JS code and need to update it.

This applies to the above `.heading` & `.paragraph` classes as well.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        var tags = postBlock.querySelectorAll('.block-news__post__tags__tag');
You can and should use ES6, i.e. `const` whenever possible, `let` only if you expect the variable to change.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        for(var key of tags.keys()) {
```suggestion
        for(const key of tags.keys()) {
```

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news-style.scss
> +$block-news__content-wrap: (
```suggestion
$block-news: (
```

1 style === 1 map which should be named the same as the main selector. Then inside you can add a key for `content-wrap` for all styles specific to content-wrap.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +				echo \wp_kses_post(Components::render('image', ['imageUrl' => $newsItem['imageUrl']]));
if you pass an additional `blockClass` argument to render method, the component should have another `blockName__image` class which you can then use inside the styles to target images inside `block-news`.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news-style.scss
> +	& .image {
See comment below inside the `news.php` of passing `blockClass` argument. That way you will be able to select this using `&__image` rather than `.image` selector.

Same applies to heading & paragraph below.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +			?>
```suggestion
		<?php foreach ($news as $newsItem) { ?>
```

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +				<span class="<?php echo esc_attr("{$blockClass}__post__meta"); ?>">
BEM classes should only have 1 element. So you can write this class as `"{$blockClass}__post-meta"`.

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +				<div class="<?php echo esc_attr("{$blockClass}__post__tags"); ?>">
See comment above, BEM classes should have only 1 element.

```suggestion
				<div class="<?php echo esc_attr("{$blockClass}__post-tags"); ?>">
```

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +					<span class="<?php echo esc_attr("btn {$blockClass}__post__tags__tag"); ?>">
```suggestion
					<span class="<?php echo esc_attr("btn {$blockClass}__post-tag"); ?>">
```

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +						<span class="<?php echo esc_attr("btn {$blockClass}__post__tags__tag"); ?>">
```suggestion
						<span class="<?php echo esc_attr("btn {$blockClass}__post-tag"); ?>">
```

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +						<span class="<?php echo esc_attr("btn {$blockClass}__post__tags__tag"); ?>">
Also if this needs to be a button, could you maybe try using the existing `button` component here? (and pass `$launch` as it's content).

As soon as you find yourself writing a class that belongs to another component (in this case `btn`) you can almost actually use that component (using `Components::render()`)

2021-07-05 09:37 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +		'buttonContent' => 'Load more',
Can you make this `Load more` content translatable?

2021-07-05 11:02 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/news.php
> +						<span class="<?php echo esc_attr("btn {$blockClass}__post__tags__tag"); ?>">
I wanted to make the element look and feel like the button component, but opted out of using the `button` component to avoid having a wrapper around every tag and to use a more semantically correct element (a generic pill-looking tag that doesn't do anything when clicked isn't really a `button`, nor is it an `a`). 

Perhaps a better way to do this would be to use `@extend .btn` in `.block-news__post-tag`?

2021-07-05 11:02 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/news.php
> +		'buttonContent' => 'Load more',
Sorry, missed that! :)

2021-07-06 01:18 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        postBlock.querySelectorAll('.block-news__post__tags__tag')[0].innerText = post.newsSite;
I've added an additional attribute `jsClass` to the image, heading and paragraphs block to be able to add `js-` prefixed tags when rendering these components in `news.php`.

2021-07-06 01:42 UTC, mbmjertan commented
This latest push includes commits from the last push in #2 as well. I've changed most of the things as @IvanGrginovInf suggested, apart from [using the button component for tags](https://github.com/mbmjertan/wp-task/pull/3/files/77c79d94946ec634cfce33050b94e5f47b5df3eb#diff-661ff1656f97a8ca822d1b44e7eb9e2f89dfa4c21e0e10e3dcb9196453139fb6), as it doesn't seem to fit semantically.

2021-07-06 07:19 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        const buttonSelector = '#block-news__button-more';
In general, IDs and classes are not ideal for JS usage due to their tendency to change (especially if you allow them to change through the WordPress editor). 

It would be better if this load more button had a js class, like `js-load-more-posts` or something similar. I've seen you've added a way to pass the JS class as an attribute in the above components, I think the button component should have this out of the box (if I'm not mistaken ofc).

I think that WP core uses data attributes instead of `js-` prefix in classes, which I kinda find odd, but that works as well 🤷🏼‍♂️

2021-07-06 07:20 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/assets/index.js
> +            fetch( '/wp-json/unicornia/v1/space-news?before='+getLastLoadedPostId(newsElem)  ).then( ( posts ) => posts.json()).then(  posts => {
While this is totally legit way to fetch info from the WP REST API, do you think there is a way to get the rest endpoint programmatically? Without explicitly writing it out?

If yes, what would be the benefit of that approach? 

Hint: think about the version parameter in the REST endpoint 😄

2021-07-06 07:30 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        newsElem.append(postBlock);
This will definitely work, but can you think of another way you could handle loading more posts from the route, without cloning the DOM elements? Think of a way to reduce the maintenance of the code.

2021-07-06 07:31 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/components/news-options.js
> +					label='Title'
This should also be translatable like the title tag above 🙂

2021-07-06 07:32 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/components/news-toolbar.js
> +		<Fragment>
If you are not using the toolbar you can remove it completely 🙂

2021-07-06 07:40 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/news.php
> +				echo \wp_kses_post(Components::render('image', [
You can actually remove the `wp_kses_post` from all the `Components::render` actually because that method is safe. You'd just need to add the `// phpcs:ignore` comment here so that the phpcs doesn't scream 😂 

The reason is that eager escaping can cause breaking down the line in the component (WP escapes some attribute that you need for something to function).

2021-07-06 07:41 UTC, dingo-d commented on unicornia/src/Blocks/custom/news/news.php
> +		'buttonContent' => __('Load more'),
When translating strings, you need to add two things here. Can you tell me what are these things you are missing?

2021-07-06 07:43 UTC, dingo-d requested changes
Left some minor questions. Great job 👍🏼

2021-07-06 08:19 UTC, IvanGrginovInf approved these changes
Left a suggestion regarding building the class string but other than that looks great!

2021-07-06 08:19 UTC, IvanGrginovInf commented on unicornia/src/Blocks/custom/news/news.php
> +					<span class="<?php echo esc_attr("btn {$blockClass}__post-tag"); ?> js-block-news-tag">
No need to change it for purposes of this task but just as a note, generally you should use the `Components::classNames` helper when you have more than 1 class on an element so there's less inline logic and it looks more clean.

Something like:

```php
$btnClasses = Components::classNames([
  'btn',
  "{$blockClass}__post-tag",
  'js-block-news-tag'
]);

...

<span class="<?php echo esc_attr($btnClasses); ?>">
```

2021-07-06 10:01 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        const buttonSelector = '#block-news__button-more';
Fixed, thanks! Missed them when adding `js-` prefixed classes.

2021-07-06 10:13 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/assets/index.js
> +            fetch( '/wp-json/unicornia/v1/space-news?before='+getLastLoadedPostId(newsElem)  ).then( ( posts ) => posts.json()).then(  posts => {
We could rely on [REST API discovery](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/). This would allow for better portability between WordPress installations. In this case, it would fix potential issues when WordPress isn't on the domain root or when pretty permalinks are displayed.

2021-07-06 10:17 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/assets/index.js
> +        newsElem.append(postBlock);
Separating `.block-news__post` into a separate component in the theme and using the `block-renderer` endpoint (https://developer.wordpress.org/rest-api/reference/rendered-blocks/) seems better.

2021-07-06 10:33 UTC, mbmjertan commented on unicornia/src/Blocks/custom/news/news.php
> +		'buttonContent' => __('Load more'),
They're missing a domain string as its second parameter, which lets WordPress identified what translation it should use.

2021-07-06 12:54 UTC, merged